  version: '3.8'
  services:
    nginx:
      build:
        context: ./requirements/nginx
      ports:
        - "443:443"
      volumes:
        - wordpress_data:/var/www/html
      networks:
        - my_network

    mariadb:
      build:
        context: ./requirements/mariadb
      environment:
        MYSQL_ROOT_PASSWORD:
        MYSQL_DATABASE:
        MYSQL_USER:
        MYSQL_PASSWORD:
      volumes:
        - mariadb_data:/var/lib/mysql
      networks:
        - my_network
      ports:
        - "3306:3306"

    wordpress:
      build:
        context: ./requirements/wordpress
      environment:
        WORDPRESS_DB_HOST: maria:3306
        WORDPRESS_DB_USER:
        WORDPRESS_DB_PASSWORD:
        WORDPRESS_DB_NAME:
      volumes:
        - wordpress_data:/var/www/html
      networks:
        - my_network
      ports:
        - "9000:9000"
  volumes:
    mariadb_data:
    wordpress_data:

  networks:
    my_network:
